spring:
  application:
    name: swagger-api-gateway

server:
  port: 11001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
  
logging:
  level:
    root: info