spring: 
  application: 
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yichengjie/config-client
          username: 626659321@qq.com
          password: y123456
server:
  port: 1201
  
