spring:
  application:
    name: eureka-client02
  cloud:
    consul:
      host: localhost
      port: 8500
#      discovery:
#        service-name: service-XXX
server:
  port: 2001
  
      